{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "3.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.26"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.26"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.26"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.2.8.jar",
          "url": "spring-boot-starter-tomcat-3.2.8.jar",
          "size": 4792,
          "sha512": "5126d5a620e630da8612f0d152fc32b951c93406b4d61b3754b773425816760e25d34b4b37bd5077b5aa77384471ce51fafd56b7220e567dadc97639557e8822",
          "sha256": "667dc7f306bb7fdcc1f0a8fe9446a3a7ed918d53eea1ce02510ecf584df07aa9",
          "sha1": "d2e1a76690ba18344f0921ee5ad507bc96fef8d6",
          "md5": "43d31d7619cf659a32ed54cd0e35577c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.26"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.26"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.26"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.2.8.jar",
          "url": "spring-boot-starter-tomcat-3.2.8.jar",
          "size": 4792,
          "sha512": "5126d5a620e630da8612f0d152fc32b951c93406b4d61b3754b773425816760e25d34b4b37bd5077b5aa77384471ce51fafd56b7220e567dadc97639557e8822",
          "sha256": "667dc7f306bb7fdcc1f0a8fe9446a3a7ed918d53eea1ce02510ecf584df07aa9",
          "sha1": "d2e1a76690ba18344f0921ee5ad507bc96fef8d6",
          "md5": "43d31d7619cf659a32ed54cd0e35577c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.2.8-javadoc.jar",
          "url": "spring-boot-starter-tomcat-3.2.8-javadoc.jar",
          "size": 4743,
          "sha512": "bbe30404bb942c1765817092d46ad3a9ae016997f29b081c5ab88581ec8c24bc03cf8240fe441d58ab8770c5bfc7322221b14b5c21141b71b877ed625ca22172",
          "sha256": "a47ba9a18873e1e496a164038d28cf6b382a10e81a02ee46c122f30f73171d16",
          "sha1": "6952656cfcab85c1f1966d522837181cdec81d2f",
          "md5": "c0e993aa2e095fde2fdad6017081dd01"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.2.8-sources.jar",
          "url": "spring-boot-starter-tomcat-3.2.8-sources.jar",
          "size": 4742,
          "sha512": "ee4a4ec0f7e9b59df15b4a21a33e2b0341e8d132b0560b578ed09bc0270b2dbc129fb8ccf044d3558f7d8f9451526a8085ad4150efdc756cc6ff9a2f4aa195f2",
          "sha256": "987883edac10e924f89ea16db2bbf6375bcb3c926025aca65bd2320f00d4ce73",
          "sha1": "482a212c5e1b05b7872e572e561c22b0f0e79f43",
          "md5": "9096c96c2a098c7041f1fec417632e4f"
        }
      ]
    }
  ]
}
