{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-security",
    "version": "3.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-security-3.2.8.jar",
          "url": "spring-boot-starter-security-3.2.8.jar",
          "size": 4742,
          "sha512": "1fd3642e5e654fa1403654b5dfb93002777acbe2c6a97ede9e1ecf638e56be795936dd3ce02c675741dbf45df50a7907dffb3aab0a7e9686b794a58ee4ab75d7",
          "sha256": "81d741ce3eade524113955734a52f366adabefdb09479c2247f3fa88008f530b",
          "sha1": "0936418206eced38b9f2f8806b5779e7a6729f19",
          "md5": "2978835593b43722a53b91b34bca8c79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-security-3.2.8.jar",
          "url": "spring-boot-starter-security-3.2.8.jar",
          "size": 4742,
          "sha512": "1fd3642e5e654fa1403654b5dfb93002777acbe2c6a97ede9e1ecf638e56be795936dd3ce02c675741dbf45df50a7907dffb3aab0a7e9686b794a58ee4ab75d7",
          "sha256": "81d741ce3eade524113955734a52f366adabefdb09479c2247f3fa88008f530b",
          "sha1": "0936418206eced38b9f2f8806b5779e7a6729f19",
          "md5": "2978835593b43722a53b91b34bca8c79"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.2.8-javadoc.jar",
          "url": "spring-boot-starter-security-3.2.8-javadoc.jar",
          "size": 4745,
          "sha512": "65d291ac82d1e12e4abb313f29f47bb87d04d1050246aa3873900d210e237dacc40be0a2da2e8a4c5625dd0ac143c90b1eac2788791718c09eed085c31fd4c34",
          "sha256": "e55921bfcfaf54015eb8d211c1d5b7f72d31919ff6b2c041f51fa086904a48bb",
          "sha1": "01e4ad76c2e73cba26fdbd2326721fda06070871",
          "md5": "dd6b5e405d58c292680e0dcbc6174bdf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.2.8-sources.jar",
          "url": "spring-boot-starter-security-3.2.8-sources.jar",
          "size": 4743,
          "sha512": "1994cdb8a5c5fd47bc5546626d7e89408a9e3a62ff8081d5fcd6bec6cda1940f9738d419e79c312a35a8afc1222e911765c29f0562edc7ae36a7e43ac648c301",
          "sha256": "0f9785575b9f46f06a8983d5f5704e9ad49597a6f0118e8bf2341e3fee910cb0",
          "sha1": "96edd7b71227952c84bfd7c2cd1084e2e713c3c4",
          "md5": "616c5e20b268b0c5c5388ade790c3e41"
        }
      ]
    }
  ]
}
