{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-gradle-plugin",
    "version": "3.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.2.8.jar",
          "url": "spring-boot-gradle-plugin-3.2.8.jar",
          "size": 143816,
          "sha512": "a72bc7f87dcdc238a80bcccd1f48ac53244dad88b6860a40406a7ad4e3650f080ad4ac8b81b3656be9474b707a75638abf30cd83779910e1f69a10a0f69f17fe",
          "sha256": "752caeb46594adcefb9824566130d35017f0c4e4056f0bd462d72a9879c6d950",
          "sha1": "32017c3be4d788e60e8c00ab7aff8e58780f135e",
          "md5": "d5ec55742e9b5a484095b945cbdf6cbc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.5",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-buildpack-platform",
          "version": {
            "requires": "3.2.8"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-loader-tools",
          "version": {
            "requires": "3.2.8"
          }
        },
        {
          "group": "io.spring.gradle",
          "module": "dependency-management-plugin",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.2.8.jar",
          "url": "spring-boot-gradle-plugin-3.2.8.jar",
          "size": 143816,
          "sha512": "a72bc7f87dcdc238a80bcccd1f48ac53244dad88b6860a40406a7ad4e3650f080ad4ac8b81b3656be9474b707a75638abf30cd83779910e1f69a10a0f69f17fe",
          "sha256": "752caeb46594adcefb9824566130d35017f0c4e4056f0bd462d72a9879c6d950",
          "sha1": "32017c3be4d788e60e8c00ab7aff8e58780f135e",
          "md5": "d5ec55742e9b5a484095b945cbdf6cbc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.2.8-javadoc.jar",
          "url": "spring-boot-gradle-plugin-3.2.8-javadoc.jar",
          "size": 319368,
          "sha512": "675523ce504e66f0b6d00e22c6763f3015152fe32c8566f9311f7b700c3950a5a1731463942ee028663e0f9d3d7f50db043c1eb854a6504b68775c401cb1ca7a",
          "sha256": "3f8b3d51766c63cccdbdfbbe3b1b8760d8711b24865091836bc5a57883c645ec",
          "sha1": "0cdde31479af8b393a2528ca52cf85503405b84d",
          "md5": "085337547f88d3ff270bdee2f894149c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.2.8-sources.jar",
          "url": "spring-boot-gradle-plugin-3.2.8-sources.jar",
          "size": 81823,
          "sha512": "4eccad1ee2a3cc38a60746e1747043bc9b40eda96c4b84f3ab38eeb054c8e6e93730f66b49330858be2d8737f4e4d24525e6ff3cc9b26d1f796ecd6712ca4ddb",
          "sha256": "0f31b504e8dcef9e763b113614cdc9f60aff558e97548f280e2456c1c3981234",
          "sha1": "6a53872bf39d091fe2e6113913670850ccc26869",
          "md5": "e171a6d05bad74ac1593f93610b60827"
        }
      ]
    },
    {
      "name": "modernGradleRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.7",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-buildpack-platform",
          "version": {
            "requires": "3.2.8"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-loader-tools",
          "version": {
            "requires": "3.2.8"
          }
        },
        {
          "group": "io.spring.gradle",
          "module": "dependency-management-plugin",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.2.8.jar",
          "url": "spring-boot-gradle-plugin-3.2.8.jar",
          "size": 143816,
          "sha512": "a72bc7f87dcdc238a80bcccd1f48ac53244dad88b6860a40406a7ad4e3650f080ad4ac8b81b3656be9474b707a75638abf30cd83779910e1f69a10a0f69f17fe",
          "sha256": "752caeb46594adcefb9824566130d35017f0c4e4056f0bd462d72a9879c6d950",
          "sha1": "32017c3be4d788e60e8c00ab7aff8e58780f135e",
          "md5": "d5ec55742e9b5a484095b945cbdf6cbc"
        }
      ]
    }
  ]
}
