{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot",
    "version": "3.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-3.2.8.jar",
          "url": "spring-boot-3.2.8.jar",
          "size": 1619917,
          "sha512": "7489f445b796c2127ab7fc77bf7bce1d7d9cc041c7cf5d75c8416b76b6e9cf8750b7f5e270c78c248eec09664ce4945856c1d8ef4a2d535ae554e480b56566f5",
          "sha256": "4c2051fe2bf70b72105f2252a211ab39db6b489e09d563f02ab90bcbc9c11470",
          "sha1": "c1724848953d313c9478587a29c07b76bbe80326",
          "md5": "02d492a8ccba04d017b15c42272e05fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-3.2.8.jar",
          "url": "spring-boot-3.2.8.jar",
          "size": 1619917,
          "sha512": "7489f445b796c2127ab7fc77bf7bce1d7d9cc041c7cf5d75c8416b76b6e9cf8750b7f5e270c78c248eec09664ce4945856c1d8ef4a2d535ae554e480b56566f5",
          "sha256": "4c2051fe2bf70b72105f2252a211ab39db6b489e09d563f02ab90bcbc9c11470",
          "sha1": "c1724848953d313c9478587a29c07b76bbe80326",
          "md5": "02d492a8ccba04d017b15c42272e05fb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.2.8-javadoc.jar",
          "url": "spring-boot-3.2.8-javadoc.jar",
          "size": 2330767,
          "sha512": "7ef885d3fe6031ad895d989c0897494488c02a0eec4a2b06d3212df9f9ec765af85deca3b6863a0a7eeb2e48fcdd8da6c80a70200c7ebf1f6caca76aa32b9bdd",
          "sha256": "c0b8fe2f63a6550389e0e53f59a5473ebf006c445dbb87b0f21e3891c005f0a7",
          "sha1": "baa3d49c8414b5c24a015c6104bd254c486648ad",
          "md5": "afa054e32e19b06dd19091a9b0eff013"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.2.8-sources.jar",
          "url": "spring-boot-3.2.8-sources.jar",
          "size": 1114870,
          "sha512": "c1ecf0dacdbfe5400bcc736d299ec5f9fbbd4a56ec449ce15b5120b5fe3e0d83a882ceb68aef074c9d432d0c2fe2ad18b8fefd95a22af6fb19e4de777708cec9",
          "sha256": "4fccd679eab09638a77c513a0093ec5049dc651723d528dab5a1abdcbb7d4e39",
          "sha1": "48138e0a740ab1c34d505114ade43121ae860ed6",
          "md5": "05678302ffc331d82d65300ab2a791cd"
        }
      ]
    }
  ]
}
