{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-core",
    "version": "6.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-crypto",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.12.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-core-6.2.5.jar",
          "url": "spring-security-core-6.2.5.jar",
          "size": 512786,
          "sha512": "f4b47a36ac1f5a701019c22f4ea1f23fa3d1341757154d64efc601b63284c9219064cd19777090bdcb78e0371345f7b1b44e9d10508d9fc0c014571474ae7f9f",
          "sha256": "68328a69f87cc410217b92fb14e02a7444bd8966eb0b58e725414f6221c823f9",
          "sha1": "6203d4c89fc322105a69407c5a413f5b1d15b2d9",
          "md5": "1b6a76318c953a317321b350ec46d9a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-crypto",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.12.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-core-6.2.5.jar",
          "url": "spring-security-core-6.2.5.jar",
          "size": 512786,
          "sha512": "f4b47a36ac1f5a701019c22f4ea1f23fa3d1341757154d64efc601b63284c9219064cd19777090bdcb78e0371345f7b1b44e9d10508d9fc0c014571474ae7f9f",
          "sha256": "68328a69f87cc410217b92fb14e02a7444bd8966eb0b58e725414f6221c823f9",
          "sha1": "6203d4c89fc322105a69407c5a413f5b1d15b2d9",
          "md5": "1b6a76318c953a317321b350ec46d9a3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-core-6.2.5-javadoc.jar",
          "url": "spring-security-core-6.2.5-javadoc.jar",
          "size": 1264316,
          "sha512": "245c91bc022fcdecf4f0bfb254a1e4112725fdc886076dc8e24ef8cdff493abd5f043b82757cd2fc8cb02da5a2b2ae4e87bdd3e068389414e9f5d42226b922cb",
          "sha256": "203224b8b8d9e812c7c85feeaebbe5a91754b3287d49874de958b264a6cdaebc",
          "sha1": "8c37be7da1fb3cc0591ff2349cbf8a94a5fddf2a",
          "md5": "ea8564ce92feb1c8bd76d1b25ccd69d6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-core-6.2.5-sources.jar",
          "url": "spring-security-core-6.2.5-sources.jar",
          "size": 504770,
          "sha512": "cafaef6148320b0733df5d8125ad9c4418e9d266038d56eaf7101eb9995e22b154439451b4d654bf28b106c88561bf32a2a0b153870e89513845689151a29b13",
          "sha256": "bdb57a419b0ce6b78540822b3d8f3de74eac3393411dd37d91f61874b6b98653",
          "sha1": "b4a2227f450b4925ee1ec19e648e7711b24cf526",
          "md5": "a8d1ac914cef103813459166762f6082"
        }
      ]
    }
  ]
}
