{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test-autoconfigure",
    "version": "3.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.8"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.2.8"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.2.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.2.8.jar",
          "url": "spring-boot-test-autoconfigure-3.2.8.jar",
          "size": 219344,
          "sha512": "871b60603a97b26fcb3084805609cf25e2d07b540295f8d9273a66137d49725079947c1127a3582d771986e3c3a004820bba2836af8a8f21fa868f34721d829f",
          "sha256": "2078a4e5d43d3fb801788d27b9a1887a3f83747ef66176f8fcd5be7c66833e8f",
          "sha1": "e8206162368de8aff9e5e49d90a1b4ee762c5230",
          "md5": "090ab3ec0c7e5b0c352dfd3b285f09cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.8"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.2.8"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.2.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.2.8.jar",
          "url": "spring-boot-test-autoconfigure-3.2.8.jar",
          "size": 219344,
          "sha512": "871b60603a97b26fcb3084805609cf25e2d07b540295f8d9273a66137d49725079947c1127a3582d771986e3c3a004820bba2836af8a8f21fa868f34721d829f",
          "sha256": "2078a4e5d43d3fb801788d27b9a1887a3f83747ef66176f8fcd5be7c66833e8f",
          "sha1": "e8206162368de8aff9e5e49d90a1b4ee762c5230",
          "md5": "090ab3ec0c7e5b0c352dfd3b285f09cc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.2.8-javadoc.jar",
          "url": "spring-boot-test-autoconfigure-3.2.8-javadoc.jar",
          "size": 488235,
          "sha512": "89a01f6402b10c189a154f7433170a40943db83779270bdf5293df54b09eec8291992bbd1f62d592ba513257c89f1838571479c57169e4f550da9342d5c168aa",
          "sha256": "7344de7ffef9d3dddb005efd1df73fdbb2c23b0d785b6eb76980ed2288e2e259",
          "sha1": "86014a578311beaca65866dcdbaa14192131b947",
          "md5": "bf522579ed23580f7e67903a20b9b510"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.2.8-sources.jar",
          "url": "spring-boot-test-autoconfigure-3.2.8-sources.jar",
          "size": 221531,
          "sha512": "3d1a220a04b32d2bf3f1a889659d83345182e84ebb4f153fa49503c51a6a51bc48940b4bcde8e35cedef8b19964e9efab0a99751a69ec47b166c3243a062bc82",
          "sha256": "dd7a8a933da120029f0a7298b2e723d9f00a7a4ef93f7b6956b96f1cc42bf929",
          "sha1": "35a698fc4ad7a18eb95360d9ea068ac3585de21d",
          "md5": "1c3771b7cb11ba4d724b6af408031762"
        }
      ]
    }
  ]
}
