{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.dataformat",
    "module": "jackson-dataformat-yaml",
    "version": "2.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-yaml-2.15.4.jar",
          "url": "jackson-dataformat-yaml-2.15.4.jar",
          "size": 53493,
          "sha512": "ce1cdbdeb498657e52c47b3c7394f92e110d12b1a52dc02dfa76ae0d8191f6ff770bd9ae8de575bcd7d519dce2e9c04dd04d8e8f3e1c395b7aeb5ed81acfd0f8",
          "sha256": "a73bd17cc0c6877801918ca0102553308dd01abad1991c8d14e3896cc03d7354",
          "sha1": "c8921aaa1584d66dd3ccf441fadae8711974147a",
          "md5": "ccb8b1b8d0d7207e53ce751bd2f0ddc3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-yaml-2.15.4.jar",
          "url": "jackson-dataformat-yaml-2.15.4.jar",
          "size": 53493,
          "sha512": "ce1cdbdeb498657e52c47b3c7394f92e110d12b1a52dc02dfa76ae0d8191f6ff770bd9ae8de575bcd7d519dce2e9c04dd04d8e8f3e1c395b7aeb5ed81acfd0f8",
          "sha256": "a73bd17cc0c6877801918ca0102553308dd01abad1991c8d14e3896cc03d7354",
          "sha1": "c8921aaa1584d66dd3ccf441fadae8711974147a",
          "md5": "ccb8b1b8d0d7207e53ce751bd2f0ddc3"
        }
      ]
    }
  ]
}
