{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-web",
    "version": "6.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-web-6.2.5.jar",
          "url": "spring-security-web-6.2.5.jar",
          "size": 781315,
          "sha512": "249019a86dcab889fa859d8f6163d4607b7f9fe84f3db3810bb7347599b013064ea2077f405fd1a5902fb1fdf9313b94c9ef4617df28ff77a300c69d83f9a2f1",
          "sha256": "bff9c7bb522718c3e14f853ffe87de27008493d582182180bf431339275e2a63",
          "sha1": "40e9b4b23b70ea7065980ef93ba3a88085008534",
          "md5": "096020f07864973805c15d1eedccf156"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-web-6.2.5.jar",
          "url": "spring-security-web-6.2.5.jar",
          "size": 781315,
          "sha512": "249019a86dcab889fa859d8f6163d4607b7f9fe84f3db3810bb7347599b013064ea2077f405fd1a5902fb1fdf9313b94c9ef4617df28ff77a300c69d83f9a2f1",
          "sha256": "bff9c7bb522718c3e14f853ffe87de27008493d582182180bf431339275e2a63",
          "sha1": "40e9b4b23b70ea7065980ef93ba3a88085008534",
          "md5": "096020f07864973805c15d1eedccf156"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-web-6.2.5-javadoc.jar",
          "url": "spring-security-web-6.2.5-javadoc.jar",
          "size": 1803059,
          "sha512": "b2f580bbed39b6ec3f1786e58956683e230d65da0276ea9c00a452bacd3151154015ea8f8aaabd4309cfc6d6c0065957ff4d41e40864e03ca6f9d0b8e1569163",
          "sha256": "f76051ec5b29fb1890f9a406a295d25a2a3ad9b66e3f07e9b13deabad6b41f01",
          "sha1": "cfdb026fdf0c16235d40f3a5fb52d1c4c5e792c8",
          "md5": "ac8d9d06683ff66ccda224fccff23f02"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-web-6.2.5-sources.jar",
          "url": "spring-security-web-6.2.5-sources.jar",
          "size": 645001,
          "sha512": "aa40412c57854d2a2e8a1ed19077c512cdf1dc93034dd7b4bf510f1bb7262bbc83463f5248bbd8ef912a6ac6f0abbe8fea9451d2351fa8394ace42b3e6900683",
          "sha256": "c072b215b2025ce9d25039f74c7df5c62189fb9e07a44254bb8afb098fc870eb",
          "sha1": "6dcb4eed1694198ee6c3741ae7a5ca2ff8aa6e2b",
          "md5": "c9e91fa82dfa6c48bed4fe755a081847"
        }
      ]
    }
  ]
}
