{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-test",
    "version": "6.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-test-6.2.5.jar",
          "url": "spring-security-test-6.2.5.jar",
          "size": 132223,
          "sha512": "36162ee9e2fed4fedd5e40f5b40fb4bb21c1b8432483b90f93559d3490f2ba2ee5bd42e64f17937b5da76f02349a08ae268b666c0934cb7f82da6b966d3dd798",
          "sha256": "51ee3ccad14ce451492016dcd31e76fb64850ac93d508a07de2ed7856d6b5def",
          "sha1": "eee512698a53361447592534370a030e254c14d3",
          "md5": "310d5d28e5d7a1b52abdf30cf5fc47f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.9"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-test-6.2.5.jar",
          "url": "spring-security-test-6.2.5.jar",
          "size": 132223,
          "sha512": "36162ee9e2fed4fedd5e40f5b40fb4bb21c1b8432483b90f93559d3490f2ba2ee5bd42e64f17937b5da76f02349a08ae268b666c0934cb7f82da6b966d3dd798",
          "sha256": "51ee3ccad14ce451492016dcd31e76fb64850ac93d508a07de2ed7856d6b5def",
          "sha1": "eee512698a53361447592534370a030e254c14d3",
          "md5": "310d5d28e5d7a1b52abdf30cf5fc47f7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-test-6.2.5-javadoc.jar",
          "url": "spring-security-test-6.2.5-javadoc.jar",
          "size": 233755,
          "sha512": "408e87648e792c1db474529c7d19e707a81d0ea2d13597d12ef0f276776a6f7d2811fb94d448b3e1e283a440f960ef353722b552576f3d5b30ea72227b00960c",
          "sha256": "fe0cda87e1e5c2a45aa33501628310c42b6e409f8263ed99ee7ee83733ab5567",
          "sha1": "1d074607260e057ae4db901a15c9dbc680ba5128",
          "md5": "03a74d5e03d79ef607b64a71f3ed9203"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-test-6.2.5-sources.jar",
          "url": "spring-security-test-6.2.5-sources.jar",
          "size": 56481,
          "sha512": "7fdb9603b2ae56b1e9bcc26d91c2429d46b66a76f9bbd2f93e423e00a8e14e89b2d2a21f568b8c72b3a6655aa7c92f1d178a1ac908a87275371490c8f7dcaee0",
          "sha256": "6a75a885283e469b3d26a849f752095c3e62dbd8e42676493e13340a2f825323",
          "sha1": "ec9b74bbb0bb18d19f292426dceb4d9c5f4d5e29",
          "md5": "ab90b6def0d29c9b3ff23c01f9256a32"
        }
      ]
    }
  ]
}
