{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-aop",
    "version": "3.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.22.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-aop-3.2.8.jar",
          "url": "spring-boot-starter-aop-3.2.8.jar",
          "size": 4769,
          "sha512": "4fe0c2d0dd8113c1fffba93c956f85ff7eea5e448209100f8de04eec4a6d6ac38f8c917b40e4103f8e698be236fec2f32deb3f2f5c797ba899812d5728ca24ba",
          "sha256": "32206880ad2d5b4c569b410d8e99f9236384c408f7cb4afe284e017912d53347",
          "sha1": "3cbbf2545ca7ddc262a0628125efb25832e25bd4",
          "md5": "333905aa659bb97558c84a7dea7fa3e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.22.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-aop-3.2.8.jar",
          "url": "spring-boot-starter-aop-3.2.8.jar",
          "size": 4769,
          "sha512": "4fe0c2d0dd8113c1fffba93c956f85ff7eea5e448209100f8de04eec4a6d6ac38f8c917b40e4103f8e698be236fec2f32deb3f2f5c797ba899812d5728ca24ba",
          "sha256": "32206880ad2d5b4c569b410d8e99f9236384c408f7cb4afe284e017912d53347",
          "sha1": "3cbbf2545ca7ddc262a0628125efb25832e25bd4",
          "md5": "333905aa659bb97558c84a7dea7fa3e2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-aop-3.2.8-javadoc.jar",
          "url": "spring-boot-starter-aop-3.2.8-javadoc.jar",
          "size": 4741,
          "sha512": "647bb80bf41d9cdb8ba8d853e4466ba04d307dff636f3f913888706c5d8ee64f5ffad22fbef4003cd952a9351c9e11ade9ecf1940aee094970edb581b989c23c",
          "sha256": "13793273eb0dc6d01349226ab919df8ad06ea5b1650992e02b356556e573b9ae",
          "sha1": "df3daf2699e8ea88ef2294dcc89ebea18433d8de",
          "md5": "71a0d8875bfa34336fa823da50dacf8c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-aop-3.2.8-sources.jar",
          "url": "spring-boot-starter-aop-3.2.8-sources.jar",
          "size": 4740,
          "sha512": "ae11a697594d3b2e3a612f2ad9068f1bce5a838600064ee4dc9b29839fe430e44e9d6843a45af3edd4a214ee148d4465c97f2bf365496a9f759c4f811a415fd4",
          "sha256": "1cdfd714f5c64c3b6c51d3170649f3edc04e6c0dc273d77224299e45d5e40672",
          "sha1": "43dc6b5765b961de02db1936d77b00155120b9b9",
          "md5": "907f9d4c039b2924bc24053bd61d9f93"
        }
      ]
    }
  ]
}
