{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test",
    "version": "3.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-3.2.8.jar",
          "url": "spring-boot-test-3.2.8.jar",
          "size": 248383,
          "sha512": "75da238936d10abce275775350bdd21e20e903f545c40a82fe3611acc3eb20e229552d1dbdf43fc224af8ea19d7d8b0b506776a04fc0864b6f2fbfa1d9464d46",
          "sha256": "f37ebd76901b54b63d9b32c9fbf5c0d269eff7e1431ef5a3a0835da4b3e1ee0f",
          "sha1": "f71933725214e6f1bb6e7562ee2d4c7d5db23702",
          "md5": "9611372cd2fbdc457045874214d570a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-3.2.8.jar",
          "url": "spring-boot-test-3.2.8.jar",
          "size": 248383,
          "sha512": "75da238936d10abce275775350bdd21e20e903f545c40a82fe3611acc3eb20e229552d1dbdf43fc224af8ea19d7d8b0b506776a04fc0864b6f2fbfa1d9464d46",
          "sha256": "f37ebd76901b54b63d9b32c9fbf5c0d269eff7e1431ef5a3a0835da4b3e1ee0f",
          "sha1": "f71933725214e6f1bb6e7562ee2d4c7d5db23702",
          "md5": "9611372cd2fbdc457045874214d570a3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.2.8-javadoc.jar",
          "url": "spring-boot-test-3.2.8-javadoc.jar",
          "size": 413952,
          "sha512": "bf26f2c6d4c73dcea5d2fb47c88470decca19d50056dabda4e99f7cccd7273af8092aff38940845a742ef18bb5c2908cbea87c6987aef889deaa8e691d07846b",
          "sha256": "d6fed1d70fee7ed4bf741642b74cf8d28fb99bb6a601763aaae249f9344ddf85",
          "sha1": "d47e6122b461c35799ea729ca30b5d433255478f",
          "md5": "07db4d6c4c76ced3587edd70e1533d87"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.2.8-sources.jar",
          "url": "spring-boot-test-3.2.8-sources.jar",
          "size": 171765,
          "sha512": "079a0a698a9d7158d27b5901cef884e9fa733386f556d6ba842fc6abf66dd7d5340a02a2c83e1195878309df44661359288ddcfa433d64b0d7075f3b86658aed",
          "sha256": "04863bb45fd8cf07cbe914e4a6a04fa1c3bea6bac820f3ce8fce065502c7126d",
          "sha1": "4f614670e4b3eb0c646ad75bc61b2244f3e05554",
          "md5": "42afe7d7ebbc6e7562771c06e8475aa0"
        }
      ]
    }
  ]
}
