{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-crypto",
    "version": "6.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.2.5.jar",
          "url": "spring-security-crypto-6.2.5.jar",
          "size": 84367,
          "sha512": "45538b89cc14197b5c12c056fc9e79ae739e311c9b67db7632be7c1e4db2a4506e96a1f23b95fb602c93e3066905d6e8bbfd8f52521b19e3a3121394f6c7b703",
          "sha256": "de5aea396b2b0d9d9f57f34cdde8567ee4b6d4ec1173539d09996452558f9112",
          "sha1": "c31136455bca4bf65f4647a6300be45ef3eb04e5",
          "md5": "2805b5e5c5fbb9a8767ba568d9128272"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.2.5.jar",
          "url": "spring-security-crypto-6.2.5.jar",
          "size": 84367,
          "sha512": "45538b89cc14197b5c12c056fc9e79ae739e311c9b67db7632be7c1e4db2a4506e96a1f23b95fb602c93e3066905d6e8bbfd8f52521b19e3a3121394f6c7b703",
          "sha256": "de5aea396b2b0d9d9f57f34cdde8567ee4b6d4ec1173539d09996452558f9112",
          "sha1": "c31136455bca4bf65f4647a6300be45ef3eb04e5",
          "md5": "2805b5e5c5fbb9a8767ba568d9128272"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.2.5-javadoc.jar",
          "url": "spring-security-crypto-6.2.5-javadoc.jar",
          "size": 225730,
          "sha512": "0b4e5f6ac2098b9195a9304c0d8faa0742c84ac660c20a4fd9b12963e0992c2de1c1d07ee5245406877e54a0277c26370f2b680c4667168a1a6ec149bf7ce069",
          "sha256": "dd26c864d2a9fc662b5642234ead860879aaf221e75ef948cf69d576d492c2c6",
          "sha1": "09e5999fdfc9fbeae5bc178b8e93181515b1e5cf",
          "md5": "2ccc71d576c90f04e4041b598eaf4f98"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.2.5-sources.jar",
          "url": "spring-security-crypto-6.2.5-sources.jar",
          "size": 76927,
          "sha512": "fe31b1f56cc968b57dd67b5b10463e0824e77f9350b9710f91b5b2fcc5079a7c7dc70162fbab57b39c0174f7d14bf04e05fe6b47532667e0adf0ec855200b961",
          "sha256": "6670d37ad18e222bf9b86abc4f8b187ab73ba95f52581e75583bd781d5fb84e7",
          "sha1": "78cac4ddabcba9d89f2c8a984ee456f2093b9078",
          "md5": "2d3eb32a1e1d1a0acb5d66dca0425186"
        }
      ]
    }
  ]
}
